# Generated by Django 5.2.15 on 2026-06-05 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMarketWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True, unique=True)),
                ('weather_status', models.CharField(choices=[('SUNNY', '맑음'), ('CLOUDY', '흐림'), ('RAINY', '비'), ('SNOWY', '눈'), ('STORMY', '폭풍')], default='SUNNY', max_length=20)),
                ('message', models.TextField()),
                ('indicator_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('market_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrendKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('keyword_name', models.CharField(max_length=100)),
                ('tf_idf_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockKeyWordMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_mappings', to='stocks.stock')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_mappings', to='stocks.trendkeyword')),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(db_index=True)),
                ('open_price', models.IntegerField()),
                ('close_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('low_price', models.IntegerField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'record_date'), name='unique_stock_date_price')],
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'stock'), name='unique_user_bookmark')],
            },
        ),
    ]
