# Generated by Django 5.2.15 on 2026-06-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("keywords", models.JSONField(default=list)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField(max_length=500, unique=True)),
                ("summary_raw", models.TextField(blank=True)),
                ("source", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="news.sector"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="SectorCardNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField(db_index=True)),
                ("headline", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("key_points", models.JSONField(default=list)),
                ("article_count", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "representative_articles",
                    models.ManyToManyField(
                        blank=True, related_name="featured_in", to="news.newsarticle"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_news",
                        to="news.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["target_date", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sector", "target_date"), name="uniq_sector_date"
                    )
                ],
            },
        ),
    ]
