# Generated by Django 5.2 on 2026-06-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_sectorstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='level',
            field=models.CharField(choices=[('LARGE', '대분류'), ('MID', '중분류')], default='MID', max_length=10),
        ),
        migrations.AddField(
            model_name='sector',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='uniq_sector_name_level'),
        ),
    ]
