# Generated by Django 5.2 on 2026-06-21 10:58

from django.db import migrations


def purge_legacy_data(apps, schema_editor):
	"""기존 10개 평면 분류로 쌓인 데이터를 비운다.

	WICS 대/중분류 체계로 재수집하므로 호환되지 않는 구버전 데이터를 삭제한다.
	(NewsArticle.sectors / SectorCardNews.representative_articles M2M는 객체 삭제 시 함께 정리된다.)
	"""
	SectorCardNews = apps.get_model('news', 'SectorCardNews')
	SectorStock = apps.get_model('news', 'SectorStock')
	NewsArticle = apps.get_model('news', 'NewsArticle')
	Sector = apps.get_model('news', 'Sector')

	SectorCardNews.objects.all().delete()
	SectorStock.objects.all().delete()
	NewsArticle.objects.all().delete()
	Sector.objects.all().delete()


class Migration(migrations.Migration):

	dependencies = [
		('news', '0003_sector_level_sector_parent_alter_sector_name_and_more'),
	]

	operations = [
		migrations.RunPython(purge_legacy_data, migrations.RunPython.noop),
	]
