# Generated by Django 5.2.15 on 2026-06-05 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='퀴즈 문제')),
                ('options', models.JSONField(verbose_name='선택지(배열)')),
                ('answer', models.CharField(max_length=100, verbose_name='정답')),
                ('explanation', models.TextField(verbose_name='해설')),
            ],
            options={
                'verbose_name': '퀴즈',
                'verbose_name_plural': '퀴즈 목록',
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100, unique=True, verbose_name='용어명')),
                ('explanation', models.TextField(verbose_name='용어 설명')),
            ],
            options={
                'verbose_name': '주식 용어',
                'verbose_name_plural': '주식 용어 목록',
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='DailyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='제공 일자')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_terms', to='tutors.term', verbose_name='용어')),
            ],
            options={
                'verbose_name': '오늘의 주식 용어',
                'verbose_name_plural': '오늘의 주식 용어 목록',
                'db_table': 'daily_term',
            },
        ),
        migrations.CreateModel(
            name='UserQuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('solved_at', models.DateTimeField(auto_now_add=True, verbose_name='풀이 일시')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tutors.quiz', verbose_name='퀴즈')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 퀴즈 풀이 이력',
                'verbose_name_plural': '사용자 퀴즈 풀이 이력 목록',
                'db_table': 'user_quiz_history',
            },
        ),
        migrations.CreateModel(
            name='UserTermReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_term_read_history',
                'unique_together': {('user', 'term')},
            },
        ),
    ]
